name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      
    - name: Import environment variables from a file
      id: import-env
      shell: bash
      run: |
        cat env.VARIABLES >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Fetch helm
      uses: wei/curl@master
      with:
        args: https://get.helm.sh/helm-v${{ env.HELM_VER }}-linux-amd64.tar.gz --output helm.tgz
        
    - name: Extract helm
      run:
        tar -xzf helm.tgz

    - name: Build and tag the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${{ env.DIND_VER }}-${{ env.HELM_VER }}
          ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:latest

